#!/bin/sh

export CLASSPATH=android/libs/scprov-jdk15-1.46.99.3-UNOFFICIAL-ROBERTO-RELEASE.jar

certificate=server/ssl/certificate.crt
default_certstore=android/res/raw/keystore.bks
password=password1
CERTSTORE=${CERTSTORE:-$default_certstore}

if [ -a $CERTSTORE ]; then
  rm $CERTSTORE || exit 1
fi

keytool \
  -import \
  -v \
  -trustcacerts \
  -alias 0 \
  -file $certificate \
  -keystore $CERTSTORE \
  -storetype BKS \
  -provider org.spongycastle.jce.provider.BouncyCastleProvider \
  -providerpath $CLASSPATH \
  -storepass $password
